import React from "react";
import properties1 from "@/assets/Images/properties1.png";
import properties2 from "@/assets/Images/properties2.png";
import properties3 from "@/assets/Images/properties3.png";

export default function useGetPropertiesForSaleData() {
  const properties = [
    {
      id: 1,
      location: "GOLDEN MILE, MARBELLA",
      title: "Boutique Living With A View",
      photo: properties1,
      bedrooms: "3 bedrooms",
      bathrooms: "3 bathrooms",
      area: "244 m²",
      price: "€ 2,250 000",
    },
    {
      id: 2,
      location: "ELVIRIA, MARBELLA EAST",
      title: "Renovated Luxury Villa",
      photo: properties2,
      bedrooms: "4 bedrooms",
      bathrooms: "2 bathrooms",
      area: "244 m²",
      price: "€ 2,250 000",
    },
    {
      id: 3,
      location: "ESTEPONA, COSTA DEL SOL",
      title: "A New Icon in Estepona",
      photo: properties3,
      bedrooms: "3 bedrooms",
      bathrooms: "3 bathrooms",
      area: "244 m²",
      price: "€ 2,250 000",
    },
    {
      id: 4,
      location: "GOLDEN MILE, MARBELLA",
      title: "Boutique Living With A View",
      photo: properties1,
      bedrooms: "3 bedrooms",
      bathrooms: "3 bathrooms",
      area: "244 m²",
      price: "€ 2,250 000",
    },
    {
      id: 5,
      location: "ELVIRIA, MARBELLA EAST",
      title: "Renovated Luxury Villa",
      photo: properties2,
      bedrooms: "4 bedrooms",
      bathrooms: "2 bathrooms",
      area: "244 m²",
      price: "€ 2,250 000",
    },
    {
      id: 6,
      location: "ESTEPONA, COSTA DEL SOL",
      title: "A New Icon in Estepona",
      photo: properties3,
      bedrooms: "3 bedrooms",
      bathrooms: "3 bathrooms",
      area: "244 m²",
      price: "€ 2,250 000",
    },
    {
      id: 7,
      location: "GOLDEN MILE, MARBELLA",
      title: "Boutique Living With A View",
      photo: properties1,
      bedrooms: "3 bedrooms",
      bathrooms: "3 bathrooms",
      area: "244 m²",
      price: "€ 2,250 000",
    },
    {
      id: 8,
      location: "ELVIRIA, MARBELLA EAST",
      title: "Renovated Luxury Villa",
      photo: properties2,
      bedrooms: "4 bedrooms",
      bathrooms: "2 bathrooms",
      area: "244 m²",
      price: "€ 2,250 000",
    },
    {
      id: 9,
      location: "ESTEPONA, COSTA DEL SOL",
      title: "A New Icon in Estepona",
      photo: properties3,
      bedrooms: "3 bedrooms",
      bathrooms: "3 bathrooms",
      area: "244 m²",
      price: "€ 2,250 000",
    },
    {
      id: 10,
      location: "GOLDEN MILE, MARBELLA",
      title: "Boutique Living With A View",
      photo: properties1,
      bedrooms: "3 bedrooms",
      bathrooms: "3 bathrooms",
      area: "244 m²",
      price: "€ 2,250 000",
    },
    {
      id: 11,
      location: "ELVIRIA, MARBELLA EAST",
      title: "Renovated Luxury Villa",
      photo: properties2,
      bedrooms: "4 bedrooms",
      bathrooms: "2 bathrooms",
      area: "244 m²",
      price: "€ 2,250 000",
    },
    {
      id: 12,
      location: "ESTEPONA, COSTA DEL SOL",
      title: "A New Icon in Estepona",
      photo: properties3,
      bedrooms: "3 bedrooms",
      bathrooms: "3 bathrooms",
      area: "244 m²",
      price: "€ 2,250 000",
    },
    {
      id: 13,
      location: "GOLDEN MILE, MARBELLA",
      title: "Boutique Living With A View",
      photo: properties1,
      bedrooms: "3 bedrooms",
      bathrooms: "3 bathrooms",
      area: "244 m²",
      price: "€ 2,250 000",
    },
    {
      id: 14,
      location: "ELVIRIA, MARBELLA EAST",
      title: "Renovated Luxury Villa",
      photo: properties2,
      bedrooms: "4 bedrooms",
      bathrooms: "2 bathrooms",
      area: "244 m²",
      price: "€ 2,250 000",
    },
    {
      id: 15,
      location: "ESTEPONA, COSTA DEL SOL",
      title: "A New Icon in Estepona",
      photo: properties3,
      bedrooms: "3 bedrooms",
      bathrooms: "3 bathrooms",
      area: "244 m²",
      price: "€ 2,250 000",
    },
  ];
  return { properties };
}
